#!/bin/bash
# warning: deletes old base image (...)

image_name=kevin_base.img
isofile=your-linux-cd.iso
image_size=10G

qemu-img create -f qcow2 $image_name $image_size

# warning: vnc listening on *:5900
qemu-system-x86_64 -machine type=q35,accel=kvm -drive file=$image_name,if=virtio,format=qcow2 -m 2G -smp 2 -balloon virtio -net nic,model=virtio -net user,hostfwd=tcp:127.0.0.1:7000-:22 -vnc :0
