#!/bin/bash

base_image_name=kevin_base.img

echo "Launching VM im management mode"
qemu-system-x86_64 -machine type=q35,accel=kvm -drive file=$base_image_name,if=virtio,format=qcow2 -m 2G -smp 2 -balloon virtio -net nic,model=virtio -net user,hostfwd=tcp:127.0.0.1:7000-:22

# you have to vnc choices:
# VNC by qemu: -vga vmware -vnc :0 (warning: unsecure)
# VNC on the host: -vga vmware; ssh -f -L 5900:localhost:5900 kevin x11vnc && vinagre localhost
